default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: sewr_development

test:
  <<: *default
  database: sewr_test

production:
  <<: *default
  database: sewr_production
