development:
  secret_key_base: 27d7163f7390e56b84ba56694408bc3f856436a0cb90bfb7f9fbb022618a320866cee4bf31b3906b70c2e073dc30dc4277c8186f63d3c081eb8e611ab5698979
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: dd94746807c7effb4543f0a4d5a5b33c4490535af9e68d792e54d095c27098901eab1c280fb29c5973ddf26cd1ab3b92a6bc72ec3608846d7aa59b7ff69d2afa
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
